### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by byte-me404** [Eshco93/dxlAPRS-SHUE#1]
Hello,
first of all thanks for this nice project, great code and documentation! While running the application I noticed a relativly high CPU usage (about 25%) even when there are currently not sonde frames reveived/processed. Is this normal? The code is running on my Raspberry Pi 4 (4GB).

Screenshot of the system running:
![Screenshot 2023-03-01 154030](https://user-images.githubusercontent.com/58748210/222172465-7db65ac0-9c93-43f2-aa61-6fafce06b49c.png)

BR
Baumi

**Comment by Eshco93** [comment]
First of all, thank you very much for your kinds words. I really appreciate that :-)

I checked this on my own system and I saw the same CPU usage that you are observing (about 25% at all times). This is of course not desirable.

I made this project public just like a week ago. I hadn't really looked at the resource utilization yet. I have now taken your problem as an opportunity to examine it more closely.
I had some threads in the project that should have been blocking, but weren't set to be blocking. Due to that, they looped all the time and because they had no sleep statement in them, they were driving up the CPU load.

This should be fixed now. With the changes I'm now seeing a CPU load of like 1 - 3 % while dxlAPRS-SHUE is processing data. Or ~0% when it's not doing anything.
