### ISSUE TITLE
M10 Serial issue?

### ISSUE THREAD

**Issue by xssfox** [Eshco93/dxlAPRS-SHUE#2]
dxlAPRS-SHUE seems to have mangled this M10 serial number so SondeHub is seeing two radiosondes with slightly different serial numbers

<img width="433" alt="image" src="https://github.com/Eshco93/dxlAPRS-SHUE/assets/59047654/010c1ff2-1098-481d-947c-3ef91cbb8ea6">
<img width="1615" alt="image" src="https://github.com/Eshco93/dxlAPRS-SHUE/assets/59047654/536a29ab-e85e-423c-bd46-835f153c6115">

**Comment by Eshco93** [comment]
First of all, thank you very much for reporting this issue.

I did a bit of research and I was able to understand how this issue came about. Actually, there are two problems that we are seeing right there. Both of them are not really bugs in dxlAPRS-SHUE, but originate from changes that were made in the latest version of sondemod. Please let me explain...

Before it's last update, sondemod provided the M10 serials without the dashes in it. Like this:

![issue1](https://github.com/Eshco93/dxlAPRS-SHUE/assets/34800304/86fa269d-431c-45d0-b5f0-a486401b1e33)

So in order to be complaint to the M10 serial format that SondeHub uses, dxlAPRS-SHUE has to add the dashes:

`# For M10 radiosondes, the serial provided by dxlAPRS is missing some dashes
if reformatted_telemetry['type'] == 'M10':
    reformatted_telemetry['serial'] = serial[0:3] + '-' + serial[3] + '-' + serial[4:]`

But in it's latest version, sondemod now includes the dashes. That means that dxlAPRS-SHUE must not add the dashes any more, when used in conjunction with the latest version of sondemod. This is an easy fix. I'll just search the M10 serial string for any dashes. If dashes are already included, none will be added. I'll soon release an updated version of dxlAPRS-SHUE that will have this fix.

The second issue is not so easy to fix. It seems like the latest version of sondemod has a bug in the M10 serial decoding. The sonde that you shared has the serial 201-2-11078. But OE3JTBs station with the latest version of sondemod decodes the serial as 001-2-11078:

![issue1](https://github.com/Eshco93/dxlAPRS-SHUE/assets/34800304/0483f296-a0dc-4fb8-bfa6-d320c9d5678e)

This is an issue in sondemod. It needs to be fixed there. But I know how to reach out to Chris, the main developer of dxlAPRS. I'll let him know about this issue. I'll share any updates that I get on this issue.

**Comment by darksidelemm** [comment]
Has there been any update on this? We are considering blocking M10 uploads from dxlAPRS-SHUE until this is resolved.

**Comment by Eshco93** [comment]
> Has there been any update on this? We are considering blocking M10 uploads from dxlAPRS-SHUE until this is resolved.

Yes, I have news regarding this issue.
Since it doesn't seem like the issue within sondemod will be fixed any time soon, I started to implement a workaround for this problem.
My workaround is calculating the actual serial of the M10 using the APRS serial (the one starting with "ME"). I already implemented this and ran a sample of 2500 M10 radiosonde serials through the calculation - it seems to work just fine.
I will update dxlAPRS-SHUE within the next few days.

**Comment by darksidelemm** [comment]
Could you please ensure this is given a new version number? That way if we continue to see the issue from stations running older versions we have the ability to block uploads from them.

**Comment by Eshco93** [comment]
> Could you please ensure this is given a new version number? That way if we continue to see the issue from stations running older versions we have the ability to block uploads from them.

Yes

**Comment by Eshco93** [comment]
I just released a new version of dxlAPRS-SHUE (1.1.2). The issue should be fixed now.
I'll try to reach out to as many dxlAPRS-SHUE users as I can and advise them to update to the latest version.
